name: Docs

on:
  pull_request:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

permissions:
  contents: read

jobs:

  docs:

    runs-on: ubuntu-latest
    name: docs
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Build docs
      run: tox -e docs
