# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python linting

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        name: [
          "flake8",
          "isort",
          "black",
        ]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run ${{ matrix.name }}
      run: tox -e ${{ matrix.name }}
